"""empty message

Revision ID: 6d1a752bb83a
Revises: 8bf6a6456ce6
Create Date: 2025-08-18 12:42:30.560633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d1a752bb83a'
down_revision = '8bf6a6456ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_agent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['assigned_agent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_agent_id')

    # ### end Alembic commands ###
